FROM eclipse-temurin:17-jdk-alpine as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

EXPOSE 8080
ENTRYPOINT ["java","-cp","app:app/lib/*","com.feastforward.FeastForwardApplication"]




# FROM eclipse-temurin:17-jdk-focal
 
# WORKDIR /backend
 
# COPY target/backend-0.0.1-SNAPSHOT.jar /backend/backend.jar

# EXPOSE 8080

# CMD ["java", "-jar", "backend.jar", "--spring.profiles.active=prod", "--spring.datasource.url=jdbc:postgresql://db:5432/postgres", "--spring.datasource.username=postgres", "--spring.datasource.password=postgres"]